version: "2"
services:

  appconf:
    image: ubuntu:16.04
    volumes:
      - ../docs/apache:/apache:ro

  rangerdb:
    image: mongo:3.2.10
    volumes:
      - ./rangerdb/volume:/data/db

  ranger:
    build: ./ranger
    volumes:
      - ./ranger:/data/ranger
      - ../test/server/data/references:/references
      - ../test/server/data:/seqdata
    command: npg_ranger_server -sdp5050 -mmongodb://rangerdb/imetacache -r /references -c /data/ranger/config.json
    entrypoint: /wait-for-it.sh rangerdb:27017 --
    links:
      - rangerdb
    depends_on:
      - rangerdb

  rangerproxy:
    build: ./rangerproxy
    ports:
      - "9090:9090"
    links:
      - ranger
    volumes_from:
      - appconf
    depends_on:
      - ranger

volumes:
  appconf:
