#cloud-config
packages:
  - avahi-daemon
  - avahi-utils
  - avahi-dnsconfd
  - mdns-scan
  - apt-transport-https
  - ca-certificates
  - htop
  - s3cmd

write_files:
  - content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd -H fd:// --dns 8.8.8.8 --dns 8.8.4.4 --bip=192.XXX.X.X/24 --mtu=1400
    path: /etc/systemd/system/docker.service.d/override.conf
  - content: |
      deb https://apt.dockerproject.org/repo ubuntu-xenial main
    path: /etc/apt/sources.list.d/docker.list

runcmd:
  - [ sh, -xc, "sed -ie \"s/localhost$/localhost $(hostname)/\" /etc/hosts" ]
  - [ perl, -i, -ple, "s/\bno\b/yes/ if /hinfo|workstation/", /etc/avahi/avahi-daemon.conf ]
  - [ systemctl, restart, avahi-daemon ]
  # to install packages signed with the key
  - [ apt-key, adv, --keyserver, "hkp://ha.pool.sks-keyservers.net:80", --recv-keys, 58118E89F3A912897C070ADBF76221572C52609D ]
  - [ apt-get, update ]
  - [ sh, -xc, "apt-get install -y linux-image-extra-$(uname -r) linux-image-extra-virtual" ]
  - [ apt-get, install, -y, docker-engine ]
  - [ systemctl, restart, docker.service ]
  # get docker compose binary
  - [ sh, -xc, "curl -L https://github.com/docker/compose/releases/download/1.9.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose" ]
  - [sh, -xc, "chmod +x /usr/local/bin/docker-compose" ]
  # add the user (ubuntu) to the docker group
  # so sudo is not required for every docker command
  - [sh, -xc, "usermod -a -G docker ubuntu" ]

ssh_authorized_keys:
  - ssh-rsa
SOMEKEY

